# Generated by Django 4.2.5 on 2023-09-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='status',
            field=models.IntegerField(choices=[(0, 'Applied'), (1, 'Processing'), (2, 'Closed')], default=0),
        ),
    ]
